trigger:
  branches:
      include:
      - main

pr:
- '*'

parameters:
  - name: parameter1
    type: string
    default: 'def1'  # Provide a default value if needed
  - name: parameter2
    type: string
    default: 'def2'

jobs:
  - job: Execute_Test_Sets
    strategy:
      matrix:
        JOB_1:
          value: 1
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - script: |
        echo "${{ parameters.parameter1 }}"
        echo "${{ parameters.parameter2 }}"
        # Add more echo statements for additional parameters
      displayName: 'Print Parameters'
    - script: |
        npm install
        npx playwright install
      displayName: 'Install Dependencies'
    - task: Bash@3
      displayName: 'UI System Tests'        
      inputs:
          targetType: 'inline'
          script: npx playwright test -g "@parabank" --workers=5 --retries=1 --shard=$(value)/1
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: always()
      inputs:
        searchFolder: 'test/test-results'
        testResultsFormat: 'JUnit'
        testResultsFiles: 'results.xml' 
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'My End-To-End Tests'
    - task: PublishPipelineArtifact@1
      condition: always()
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/test/test-results
        artifactName: TestResults_$(value)
